Assignment Given : 30/01/2025 || Submission Date : 30/01/2025 || Deadline : 04/02/2025 6PM

In [51]:
import numpy as np

Q1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

In [56]:
array = np.array([6, 10, 14, 16, 20])
print("After Adding 2 : ",array+2)

After Adding 2 :  [ 8 12 16 18 22]


b) Multiply 3 with all the elements

In [57]:
print("After Multiplying by 3 : ",array*3)

After Multiplying by 3 :  [18 30 42 48 60]


c) Divide every element by 2

In [58]:
print("After Dividing by 2 : ",array/2)

After Dividing by 2 :  [ 3.  5.  7.  8. 10.]


Q2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [59]:
arr = np.array([1,2,3,6,4,5])
arr[::-1]

array([5, 4, 6, 3, 2, 1])

b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [60]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
a,b = np.unique(x, return_counts=True)
elementx = (a[np.argmax(b)])
indexx = np.where(x == elementx)
print("Max occurrence is of : ",elementx)
print("Indices : ",indexx[0])

Max occurrence is of :  1
Indices :  [0 5 7 8 9]


In [61]:
c,d = np.unique(y, return_counts=True)
elementy = (c[np.argmax(d)])
indexy = np.where(y == elementy)
print("Max occurrence is of : ",elementy)
print("Indices : ",indexy[0])

Max occurrence is of :  1
Indices :  [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [62]:
arr3 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("1st Row 2nd Col : ",arr3[0,1])
print("3rd Row 1st Col : ",arr3[2,0])

1st Row 2nd Col :  20
3rd Row 1st Col :  70


Q.4 Write program to create an 1-D NumPy array named YourName with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [63]:
jatinkalra = np.linspace(10,100,25)
print("Dimension : ",jatinkalra.ndim)
print("Shape : ",jatinkalra.shape)
print("Total Elements : ",jatinkalra.size)
print("Data Type : ",jatinkalra.dtype)
print("Total Bytes : ",jatinkalra.nbytes)
print("Transpose using reshape :",jatinkalra.reshape(25,1))
print("Transpose using T : ",jatinkalra.T)

Dimension :  1
Shape :  (25,)
Total Elements :  25
Data Type :  float64
Total Bytes :  200
Transpose using reshape : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T :  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_yourname
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_yourname. Resize the array to two rows and three
columns and name it as resized_ ucs420_yourname

In [64]:
ucs420_jatinkalra = np.array([10,20,30,40,50,60,70,80,90,15,20,35])
print("Mean : ",np.mean(ucs420_jatinkalra))
print("Median : ",np.median(ucs420_jatinkalra))
print("Max : ",np.max(ucs420_jatinkalra))
print("Min : ",np.min(ucs420_jatinkalra))
print("Unique : ",np.unique(ucs420_jatinkalra))
reshaped_ucs420_jatinkalra = ucs420_jatinkalra.reshape(4,3)
print("Reshaped : ",reshaped_ucs420_jatinkalra)
resized_ucs420_jatinkalra = np.resize(ucs420_jatinkalra,(2,3))
print("Resized : ",resized_ucs420_jatinkalra)

Mean :  43.333333333333336
Median :  37.5
Max :  90
Min :  10
Unique :  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped :  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized :  [[10 20 30]
 [40 50 60]]
